from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


# ---------------------------------------------------
# UTILITIES
# ---------------------------------------------------

def run_command(command: list[str]):
    print(f"\nRunning: {' '.join(command)}\n")
    result = subprocess.run(command)
    if result.returncode != 0:
        print(f"Command failed: {' '.join(command)}")
        sys.exit(1)


def write_file(path: str, content: str):
    file_path = ROOT / path
    file_path.parent.mkdir(parents=True, exist_ok=True)

    if not file_path.exists():
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content.strip() + "\n")
        print(f"Created: {path}")


def ensure_dir(path: str):
    (ROOT / path).mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------
# REQUIREMENTS
# ---------------------------------------------------

REQUIREMENTS = """
flask
requests
sqlalchemy
psycopg2-binary
python-dotenv
numpy
pandas
tqdm
"""

# ---------------------------------------------------
# FILE BOOTSTRAP
# ---------------------------------------------------

FILES = {

"requirements.txt": REQUIREMENTS,

".env.example": """
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/tournament
SIMULATION_RUNS=100000
""",

"docs/PROJECT_MIGRATION.md": """
# Project Migration Guide

This document allows a new AI or developer to quickly understand the system.

System Purpose
--------------
NCAA tournament simulation platform capable of:

• harvesting NCAA data
• building team and player features
• simulating games
• running Monte Carlo tournament simulations
• generating narrative explanations
• publishing blog-style analysis
• serving results through API + dashboard

Architecture Layers
-------------------

builders
database
ingestion
simulation
publishing
api
dashboard

Primary Commands
----------------

Build system

    python scripts/build.py all

Run ingestion

    python services/ingestion_worker/run_pipelines.py

Run simulation

    python services/simulation_worker/run_full_tournament_simulation.py

Run Monte Carlo

    python services/simulation_worker/run_massive_monte_carlo.py
""",

"data/README.md": """
Data Directory

raw/
    raw ingested data

staged/
    normalized ingestion data

curated/
    cleaned modeling data

features/
    engineered features

simulation-inputs/
    data used for simulation

simulation-outputs/
    results generated by simulations
""",

"governance/architecture/architecture.md": """
# Architecture

Layers

1 ingestion
2 database
3 feature engineering
4 simulation engine
5 monte carlo engine
6 narrative generation
7 publishing
8 API
9 dashboard
""",

"scripts/run_complete_pipeline.py": """
import subprocess

def run(cmd):
    print(f"Running: {cmd}")
    subprocess.run(cmd, shell=True, check=True)

def main():

    print("Starting complete pipeline")

    run("python services/ingestion_worker/run_pipelines.py")
    run("python services/simulation_worker/run_simulations.py")
    run("python services/simulation_worker/run_massive_monte_carlo.py")

    print("Pipeline complete")

if __name__ == "__main__":
    main()
"""
}


# ---------------------------------------------------
# BOOTSTRAP STEPS
# ---------------------------------------------------

def bootstrap_files():
    print("\nCreating system files...\n")
    for path, content in FILES.items():
        write_file(path, content)


def bootstrap_directories():
    print("\nCreating directories...\n")

    dirs = [
        "data/raw",
        "data/staged",
        "data/curated",
        "data/features",
        "data/simulation-inputs",
        "data/simulation-outputs",
        "data/audit",
        "docs",
        "governance",
        "experiments",
        "tests",
    ]

    for d in dirs:
        ensure_dir(d)


def install_requirements():
    print("\nInstalling dependencies...\n")
    run_command([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])


def build_system():
    print("\nRunning system builders...\n")
    run_command([sys.executable, "scripts/build.py", "all"])


def run_migrations():
    print("\nRunning database migrations...\n")

    migration_script = ROOT / "packages/db/run_migrations.py"

    if migration_script.exists():
        run_command([sys.executable, str(migration_script)])
    else:
        print("Migration script not found — skipping.")


def harvest_data():
    print("\nRunning ingestion pipelines...\n")

    runner = ROOT / "services/ingestion_worker/run_pipelines.py"

    if runner.exists():
        run_command([sys.executable, str(runner)])
    else:
        print("Pipeline runner not found — skipping.")


def run_simulations():
    print("\nRunning simulations...\n")

    sim = ROOT / "services/simulation_worker/run_simulations.py"

    if sim.exists():
        run_command([sys.executable, str(sim)])
    else:
        print("Simulation runner not found — skipping.")


# ---------------------------------------------------
# MAIN
# ---------------------------------------------------

def main():

    print("\n==============================")
    print("NAACP TOURNAMENT SYSTEM SETUP")
    print("==============================\n")

    bootstrap_directories()
    bootstrap_files()

    install_requirements()

    build_system()

    run_migrations()

    harvest_data()

    run_simulations()

    print("\nSystem bootstrap complete.\n")
    print("You can now run:")
    print("python scripts/run_complete_pipeline.py\n")


if __name__ == "__main__":
    main()